---
before_install:
- gem install hoe-travis minitest-matchers --no-rdoc --no-ri
before_script:
- rake travis:before -t
language: ruby
notifications:
  email:
  - mike@blowmage.com
rvm:
- 2.3.1
- 2.2.5
- 2.1.9
- 2.0.0-p648
- 1.9.3
- ruby-head
script: rake travis
