---
before_install:
  - gem update --system
  - gem --version
script:
- bundle exec rake
language: ruby
notifications:
  email:
  - mike@blowmage.com
rvm:
- 2.3.1
- 2.2.5
- 2.1.9
- 2.0.0-p648
- 1.9.3
- ruby-head
